spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_db?characterEncoding=utf8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: root
